# Generated by Django 3.1 on 2020-08-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0002_auto_20200829_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
