# Generated by Django 3.1 on 2020-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0003_remove_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Destinations')),
                ('description', models.CharField(max_length=200)),
                ('offer', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
