# Generated by Django 3.1 on 2020-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kings', '0004_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='nights',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
